spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.107/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    #redis 配置
  redis:
    database: 0
    host: 192.168.0.107
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 8
      max-idle: 0
    timeout: 0
# jsp 配置
 #http:
 #  encoding:
 #    force: true
 #    charset: utf-8
 #    enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false
#顶级目录
#server:
#  context-path: /
  #tomcat:
  #  uri-encoding: UTF-8
  #port: 8080

